### ISSUE TITLE
Scale issue ?

### ISSUE THREAD

**Issue by Steelskinz** [alessiocali/card-tiles#29]
System : Custom System Builder
Foundry : Up to date V10 something.
Module : Up to date :  0.2.2

Error log : 
![image](https://user-images.githubusercontent.com/93941729/209696333-253cfa57-67f1-40a7-8f25-f0e3db101f14.png)
![image](https://user-images.githubusercontent.com/93941729/209696409-ad1a9216-6a59-4532-af8f-71c88743ca10.png)

Description : When a card is placed as a tile, even by changing the size in parameters it's really really small.

**Comment by alessiocali** [comment]
I can't seem to be able to reproduce your issue, are you sure it's not a conflicting module?

**Comment by TheLaslo** [comment]
Scale of placed cards are in pixels and should probably be in grid units.

**Comment by alessiocali** [comment]
Interesting. I assume @Steelskinz has a very large grid in their example?

**Comment by Steelskinz** [comment]
I though of that too at first but even with a smaller grid it was doing it. However I retried after reading your message and everything is working well, I guess it was maybe a cache issue?

**Comment by TheLaslo** [comment]
The smallest resolution grid in Foundry is 50px / square so you would have to set your card config to reflect your resolution.  so like 50 wide x 100 high.  That's why I think using grid units would make more sense and you wouldn't have to change the size of your cards based on grid resolution of your scene.

**Comment by benjamin-ping-xu** [comment]
I'm having a similar issue. 

**System**: D&D5e
**Modules**: Tested w/ just Card Tiles, Monk's Active Tile Triggers, and Warp Gate, and also with a more complex module setup (40+). Issue persisted in both. 

**Main Issue:** Cannot change the default size of placed cards. 

Dragging a card from either the deck or a stack onto the canvas always defaults to a size of 2px by 3px.
Neither the 'Default Card Height'/'Default Card Width' in Module Settings nor the 'Default Dimensions' (Width, Height) under Configuration for the deck seem to have any effect. Rotation value also does nothing. 
The Card Tiles setting for 'Default Card Scaling' works--if set to the max, 10, the cards are now created 20px by 30px. But this is still far too small for practical use. 

There is an inconsistent issue (I can't replicate it 100% of the time) where mousing over the newly created tile will repeatedly throw an exception:

```
Uncaught TypeError: undefined. Cannot read properties of null (reading 'scale')
[No packages detected]
    at ResizeHandle.get (display.min.mjs:8:8955)
    at Tile._onHandleHoverOut (foundry.js:45398:12)
    at Tile._onHoverOut (foundry.js:45296:35)
    at MouseInteractionManager.callback (foundry.js:27813:45)
    at MouseInteractionManager._handleMouseOut (foundry.js:27952:17)
    at a.emit (index.js:181:35)
    at r.dispatchEvent (interaction.min.mjs:8:12235)
    at r.processPointerOverOut (interaction.min.mjs:8:18331)
    at r.processPointerMove (interaction.min.mjs:8:17115)
    at t.recursiveFindHit (interaction.min.mjs:8:4098)
    at t.recursiveFindHit (interaction.min.mjs:8:3882)
    at t.recursiveFindHit (interaction.min.mjs:8:3882)
    at t.recursiveFindHit (interaction.min.mjs:8:3882)
    at t.recursiveFindHit (interaction.min.mjs:8:3882)
    at t.recursiveFindHit (interaction.min.mjs:8:3882)
    at t.findHit (interaction.min.mjs:8:4157)
    at r.processInteractive (interaction.min.mjs:8:12841)
    at r.onPointerMove (interaction.min.mjs:8:16687)
```

But if I then edit the tile properties manually and change the Tile Scale (Horizontal, Vertical), the error no longer occurs. 

Please let me know if there's any other information I can provide that would help.
